### ISSUE TITLE
mod_game\privacy\provider::delete_data_for_user

### ISSUE THREAD

**Issue by ger82** [bdaloukas/moodle-mod_game#37]
#0 /moodle/lib/dml/mysqli_native_moodle_database.php(1686): moodle_database->query_end(false)
#1 /moodle/lib/dml/moodle_database.php(1977): mysqli_native_moodle_database->delete_records_select('game_grades', 'WHERE game = ? ...', Array)
#2 /moodle/mod/game/lib.php(1566): moodle_database->delete_records('game_grades', Array)
#3 /moodle/mod/game/classes/privacy/provider.php(317): game_delete_user_attempts('2', Object(stdClass))
#4 /moodle/lib/moodlelib.php(8098): mod_game\privacy\provider::delete_data_for_user(Object(core_privacy\local\request\approved_contextlist))
#5 /moodle/privacy/classes/manager.php(578): component_class_callback('mod_game\\privac...', 'delete_data_for...', Array)
#6 /moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('mod_game', 'core_privacy\\lo...', 'delete_data_for...', Array)
#7 /moodle/privacy/classes/manager.php(415): core_privacy\manager->handled_component_class_callback('mod_game', 'core_privacy\\lo...', 'delete_data_for...', Array)
#8 /moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(138): core_privacy\manager->delete_data_for_user(Object(core_privacy\local\request\contextlist_collection))
#9 /moodle/lib/cronlib.php(333): tool_dataprivacy\task\process_data_request_task->execute()
#10 /moodle/lib/cronlib.php(198): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#11 /moodle/lib/cronlib.php(76): cron_run_adhoc_tasks(1612355461)
#12 /moodle/admin/cli/cron.php(79): cron_run()
#13 {main}

**Comment by tholudwig** [comment]
I think the problem occurs, because the plugin is not fully supporting moodles privacy api. Running /admin/tool/dataprivacy/pluginregistry.php says "Userlist-Provider is missing".
