### ISSUE TITLE
Exception pr. mail to admins

### ISSUE THREAD

**Issue by neeesn** [bdaloukas/moodle-mod_game#73]
Hi Im getting this error pr email.

An exception occurred while calling mod_game\privacy\provider::delete_data_for_user.
This means that the mod_game plugin did not complete the data processing. The following information can be provided to the plugin developer:

Field "game" does not exist in the table game_grades.
#0 /var/www/html/moodle/lib/dml/moodle_database.php(2051): moodle_database->where_clause()
#1 /var/www/html/moodle/mod/game/lib.php(1666): moodle_database->delete_records()
#2 /var/www/html/moodle/mod/game/classes/privacy/provider.php(316): game_delete_user_attempts()
#3 /var/www/html/moodle/lib/moodlelib.php(7817): mod_game\privacy\provider::delete_data_for_user()
#4 /var/www/html/moodle/privacy/classes/manager.php(578): component_class_callback()
#5 /var/www/html/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#6 /var/www/html/moodle/privacy/classes/manager.php(414): core_privacy\manager->handled_component_class_callback()
#7 /var/www/html/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(151): core_privacy\manager->delete_data_for_user()
#8 /var/www/html/moodle/lib/classes/cron.php(519): tool_dataprivacy\task\process_data_request_task->execute()
#9 /var/www/html/moodle/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task()
#10 /var/www/html/moodle/lib/classes/cron.php(128): core\cron::run_adhoc_tasks()
#11 /var/www/html/moodle/admin/cli/cron.php(186): core\cron::run_main_process()
#12 {main}

We are on Moodle version 4.4.4 2024042204.04 and plugin 2024100400 Moodle 3.0 - 4.5

**Comment by bdaloukas** [comment]
Thanks for the message.
Version 2024120500 fixes the above problem.
